server:
  port: 7778



spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848



  main:
    allow-bean-definition-overriding: true